### ISSUE TITLE
数组维度问题报错

### ISSUE THREAD

**Issue by EticosCheng** [bubbliiiing/detr-pytorch#2]
你好！训练阶段出现异常：

![image](https://user-images.githubusercontent.com/42287238/223041403-a49f83f5-f00a-4b7e-b2d7-55493b5ccbb5.png)

**Comment by bubbliiiing** [comment]
呀，是最近下的嘛

**Comment by EticosCheng** [comment]
> 呀，是最近下的嘛

是的，最近下了你的很多模型，改改直接就能跑太方便了，给你十个好评。这个模型的话一开始就因为维度问题停止运行。在Efficientdet（Pytorch）训练中包括结束后的评估阶段会提示未检出任何目标，ap和map全为0

**Comment by bubbliiiing** [comment]
好的，就是某个图数据增强后没找到目标，我改改

**Comment by cc-guowenchang** [comment]
请问改了吗，我也出现了这样的问题

**Comment by bubbliiiing** [comment]
pull 一下

**Comment by EticosCheng** [comment]
> pull 一下
谢谢巨佬
