### ISSUE TITLE
模型未进行梯度更新

### ISSUE THREAD

**Issue by WinnerMeat** [bubbliiiing/detr-pytorch#6]
b导，我在运行你的代码训练自己的数据集100个epoch后，发现map异常低。在比较第100个epoch和第50个epoch时发现里面的weight都是一样的，并未更新模型的weight（其他epoch都是这样），不知道该问题如何解决。
训练数据集为COCO数据集，数据格式类型并没有问题。
![image](https://user-images.githubusercontent.com/53172668/226077842-23febe3e-c2e7-4892-bb59-5b09091f8c3c.png)

**Comment by WinnerMeat** [comment]
optimizer的问题，已解决

**Comment by baosongliang** [comment]
> optimizer的问题，已解决

哪里出了问题？

**Comment by WinnerMeat** [comment]
![image](https://user-images.githubusercontent.com/53172668/226497990-7b8932bc-c697-4160-a2b6-766e75eee0eb.png)
应该是这里的问题，我改了后模型有更新，由于是新手，所以不知道如何改才是最优的解决方案，如果有更好的办法，请告知，谢谢

**Comment by bubbliiiing** [comment]
为啥呀……不太理解，我不是分了四次加进optimizer吗
